### ISSUE TITLE
Create a Readme file

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/dsc#2]
### Add a `README.md` file with 

- [x]  Title ```<h1 align='center'>dsc-website</h1>```
- [x]  Description like  `Website for DSC IIIT Vadodara Chapter`
- [x]  How to setup

**Comment by anshumanv** [comment]
Bhai rest karle, happy diwali.

**Comment by Shreyansh-Mishra** [comment]
I would like to work on this issue @iiitv/project-maintainers
