### ISSUE TITLE
Add build badges 

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/dsc#3]
After #2 completes , add badges 

Use can create badges using https://shields.io 

You can look our other project if needs a reference https://github.com/iiitv/getmein-web

**Comment by Shreyansh-Mishra** [comment]
I would like to work on this issue @iiitv/project-maintainers

**Comment by AmanRaj1608** [comment]
Are u assigned to more than 2 projects?

**Comment by Shreyansh-Mishra** [comment]
yes, but i have finished working on #2

**Comment by AmanRaj1608** [comment]
GFI @Shreyansh-Mishra
